title = "Ilona Loučková"
owner = "Ilona Loučková"
copyright = "Ilona Loučková"
baseURL = "https://ilxnah.github.io/resume/"
theme = "resume"
languageCode = "en-us"
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
gitCommitPrefix = "https://github.com/ILXNAH/resume/commit"
favicon = "icons/favicon.ico"
profileImage = "images/inguz.png"