theme = "resume"
baseURL = "https://ilxnah.github.io/resume/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

enableGitInfo = true

[params]
gitCommitPrefix = "https://github.com/ILXNAH/resume/commit"