name: Deploy Hugo site to GitHub Pages
on: {push: {branches: [main], paths: ['assets/**','content/**','data/**','layouts/**','static/**','themes/**','config.toml','.github/workflows/**']}, workflow_dispatch: {}}
permissions: {contents: read, pages: write, id-token: write}
concurrency: {group: pages, cancel-in-progress: true}
defaults: {run: {shell: bash}}
jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    outputs: {"run": "${{ steps.diff.outputs.run }}"}
    steps: [{uses: actions/checkout@v4, with: {fetch-depth: 0}}, { id: diff, run: 'B="${{ github.event.before }}"; [[ -z "$B" || "$B" == 0000000000000000000000000000000000000000 ]] && { echo run=true>>$GITHUB_OUTPUT; exit 0; }; git cat-file -e "$B^{commit}" 2>/dev/null || { echo run=true>>$GITHUB_OUTPUT; exit 0; }; C="$(git diff --name-only "$B" "${{ github.sha }}" -- assets/ content/ data/ layouts/ static/ themes/ config.toml)"; [[ -n "$C" ]] && echo run=true>>$GITHUB_OUTPUT || echo run=false>>$GITHUB_OUTPUT' }]
  build:
    if: github.event_name == 'workflow_dispatch' || needs.changes.outputs.run == 'true'
    needs: changes
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env: {HUGO_VERSION: 0.141.0, HUGO_ENVIRONMENT: production, HUGO_CACHEDIR: '${{ github.workspace }}/.hugo_cache'}
    steps:
      - {uses: peaceiris/actions-hugo@v2, with: {hugo-version: '${{ env.HUGO_VERSION }}', extended: true}}
      - {uses: actions/checkout@v4, with: {submodules: recursive, fetch-depth: 0}}
      - {id: pages, uses: actions/configure-pages@v5}
      - {uses: actions/cache/restore@v4, continue-on-error: true, with: { path: "${{ env.HUGO_CACHEDIR }}", key: "${{ runner.os }}-hugo-${{ env.HUGO_VERSION }}-${{ hashFiles('config.toml') }}", restore-keys: "${{ runner.os }}-hugo-${{ env.HUGO_VERSION }}-\n${{ runner.os }}-hugo-" }}
      - {run: 'HUGO_LATEST_COMMIT="$(git rev-parse --short HEAD)" hugo --gc --minify --enableGitInfo --baseURL "${{ steps.pages.outputs.base_url }}/"'}
      - {if: always(), uses: actions/cache/save@v4, continue-on-error: true, with: { path: "${{ env.HUGO_CACHEDIR }}", key: "${{ runner.os }}-hugo-${{ env.HUGO_VERSION }}-${{ hashFiles('config.toml') }}" }}
      - {uses: actions/upload-pages-artifact@v3, with: { path: ./public, retention-days: 90 }}
  deploy:
    if: github.event_name == 'workflow_dispatch' || needs.changes.outputs.run == 'true'
    needs: [changes, build]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    environment: {name: github-pages, url: '${{ steps.deployment.outputs.page_url }}'}
    steps: [{id: deployment, uses: actions/deploy-pages@v4}]